"""ORM models package.

Importing this package registers every model on ``Base.metadata`` (Alembic's
``target_metadata``). Re-exports the Base + all entities for convenient imports.
"""

from app.models.base import Base
from app.models.billing import BillingRate
from app.models.catalog_refresh import CatalogReportArtifact, CatalogOperatorAction
from app.models.execution import DiagnosisClaim, ExecutionRuntime, ModelSelection, ExecutionRevision
from app.models.orm import (
    AgentRuntimeConfig,
    Benchmark,
    BenchmarkResult,
    CatalogBenchmarkFamily,
    CatalogBenchmarkVersion,
    CatalogEvaluator,
    CatalogMetricDefinition,
    CatalogModel,
    CatalogModelAlias,
    CatalogObservation,
    CatalogObservationMetric,
    CatalogProtocol,
    CatalogProvider,
    CatalogProviderDeployment,
    CatalogSource,
    CatalogSourceSnapshot,
    CatalogImportState,
    CatalogSourcePayload,
    CatalogSnapshotLifecycle,
    CatalogTaskBenchmark,
    ChatMessage,
    CiFinding,
    CiRun,
    FindingFeedback,
    Harness,
    JenkinsConnection,
    LlmCall,
    LlmUsage,
    Model,
    Project,
    RecommendationEvidence,
    RecommendationOption,
    RequirementsProfile,
    RetrievalTrace,
    SourceDocument,
    User,
)

__all__ = [
    "CatalogReportArtifact", "CatalogOperatorAction",
    "BillingRate",
    "DiagnosisClaim", "ExecutionRuntime", "ModelSelection", "ExecutionRevision",
    "AgentRuntimeConfig",
    "Base",
    "Benchmark",
    "BenchmarkResult",
    "CatalogBenchmarkFamily",
    "CatalogBenchmarkVersion",
    "CatalogEvaluator",
    "CatalogMetricDefinition",
    "CatalogModel",
    "CatalogModelAlias",
    "CatalogObservation",
    "CatalogObservationMetric",
    "CatalogProtocol",
    "CatalogProvider",
    "CatalogProviderDeployment",
    "CatalogSource",
    "CatalogSourceSnapshot",
    "CatalogImportState",
    "CatalogSourcePayload",
    "CatalogSnapshotLifecycle",
    "CatalogTaskBenchmark",
    "ChatMessage",
    "CiFinding",
    "CiRun",
    "FindingFeedback",
    "Harness",
    "JenkinsConnection",
    "LlmCall",
    "LlmUsage",
    "Model",
    "Project",
    "RecommendationEvidence",
    "RecommendationOption",
    "RequirementsProfile",
    "RetrievalTrace",
    "SourceDocument",
    "User",
]
